layout_spectrum: 1
color:
  saturation: 0.3936679
  brandStrength: 0.4342891
  lightness: 0.6553166
  rhythmicContrast: 0.4569892
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.4749103
name: ArturoCarlos
